#!/bin/bash
sox china/china0.wav -t sl --encoding signed-integer --bits 32 --endian big china/china0.sl silence 20s 0s -76d trim 0s
sox china/china1.wav -t sl --encoding signed-integer --bits 32 --endian big china/china1.sl silence 20s 0s -76d trim 0s
sox china/china2.wav -t sl --encoding signed-integer --bits 32 --endian big china/china2.sl silence 20s 0s -76d trim 0s
sox china/china3.wav -t sl --encoding signed-integer --bits 32 --endian big china/china3.sl silence 20s 0s -76d trim 0s
sox china/china4.wav -t sl --encoding signed-integer --bits 32 --endian big china/china4.sl silence 20s 0s -76d trim 0s
sox china/china5.wav -t sl --encoding signed-integer --bits 32 --endian big china/china5.sl silence 20s 0s -76d trim 0s
sox china/china6.wav -t sl --encoding signed-integer --bits 32 --endian big china/china6.sl silence 20s 0s -76d trim 0s
sox china/china7.wav -t sl --encoding signed-integer --bits 32 --endian big china/china7.sl silence 20s 0s -76d trim 0s
sox china/china8.wav -t sl --encoding signed-integer --bits 32 --endian big china/china8.sl silence 20s 0s -76d trim 0s
sox china/china9.wav -t sl --encoding signed-integer --bits 32 --endian big china/china9.sl silence 20s 0s -76d trim 0s
sox crash1/crash10.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash10.sl silence 20s 0s -76d trim 0s
sox crash1/crash11.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash11.sl silence 20s 0s -76d trim 0s
sox crash1/crash12.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash12.sl silence 20s 0s -76d trim 0s
sox crash1/crash13.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash13.sl silence 20s 0s -76d trim 0s
sox crash1/crash14.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash14.sl silence 20s 0s -76d trim 0s
sox crash1/crash15.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash15.sl silence 20s 0s -76d trim 0s
sox crash1/crash16.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash16.sl silence 20s 0s -76d trim 0s
sox crash1/crash17.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash17.sl silence 20s 0s -76d trim 0s
sox crash1/crash18.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash18.sl silence 20s 0s -76d trim 0s
sox crash1/crash19.wav -t sl --encoding signed-integer --bits 32 --endian big crash1/crash19.sl silence 20s 0s -76d trim 0s
sox crash2/crash20.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash20.sl silence 20s 0s -76d trim 0s
sox crash2/crash21.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash21.sl silence 20s 0s -76d trim 0s
sox crash2/crash22.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash22.sl silence 20s 0s -76d trim 0s
sox crash2/crash23.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash23.sl silence 20s 0s -76d trim 0s
sox crash2/crash24.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash24.sl silence 20s 0s -76d trim 0s
sox crash2/crash25.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash25.sl silence 20s 0s -76d trim 0s
sox crash2/crash26.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash26.sl silence 20s 0s -76d trim 0s
sox crash2/crash27.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash27.sl silence 20s 0s -76d trim 0s
sox crash2/crash28.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash28.sl silence 20s 0s -76d trim 0s
sox crash2/crash29.wav -t sl --encoding signed-integer --bits 32 --endian big crash2/crash29.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi0.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi0.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi1.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi1.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi2.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi2.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi3.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi3.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi4.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi4.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi5.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi5.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi6.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi6.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi7.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi7.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi8.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi8.sl silence 20s 0s -76d trim 0s
sox floor_hi/floor_hi9.wav -t sl --encoding signed-integer --bits 32 --endian big floor_hi/floor_hi9.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo0.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo0.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo1.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo1.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo2.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo2.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo3.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo3.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo4.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo4.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo5.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo5.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo6.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo6.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo7.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo7.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo8.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo8.sl silence 20s 0s -76d trim 0s
sox floor_lo/floor_lo9.wav -t sl --encoding signed-integer --bits 32 --endian big floor_lo/floor_lo9.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls0.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls0.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls1.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls1.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls2.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls2.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls3.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls3.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls4.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls4.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls5.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls5.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls6.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls6.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls7.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls7.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls8.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls8.sl silence 20s 0s -76d trim 0s
sox hihat_cls/hihat_cls9.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_cls/hihat_cls9.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn0.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn0.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn1.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn1.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn2.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn2.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn3.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn3.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn4.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn4.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn5.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn5.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn6.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn6.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn7.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn7.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn8.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn8.sl silence 20s 0s -76d trim 0s
sox hihat_opn/hihat_opn9.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_opn/hihat_opn9.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped0.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped0.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped1.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped1.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped2.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped2.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped3.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped3.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped4.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped4.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped5.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped5.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped6.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped6.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped7.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped7.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped8.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped8.sl silence 20s 0s -76d trim 0s
sox hihat_ped/hihat_ped9.wav -t sl --encoding signed-integer --bits 32 --endian big hihat_ped/hihat_ped9.sl silence 20s 0s -76d trim 0s
sox kick_a/kick_a0.wav -t sl --encoding signed-integer --bits 32 --endian big kick_a/kick_a0.sl silence 20s 0s -76d trim 0s
sox kick_a/kick_a1.wav -t sl --encoding signed-integer --bits 32 --endian big kick_a/kick_a1.sl silence 20s 0s -76d trim 0s
sox kick_a/kick_a2.wav -t sl --encoding signed-integer --bits 32 --endian big kick_a/kick_a2.sl silence 20s 0s -76d trim 0s
sox kick_a/kick_a3.wav -t sl --encoding signed-integer --bits 32 --endian big kick_a/kick_a3.sl silence 20s 0s -76d trim 0s
sox kick_a/kick_a4.wav -t sl --encoding signed-integer --bits 32 --endian big kick_a/kick_a4.sl silence 20s 0s -76d trim 0s
sox kick_a/kick_a5.wav -t sl --encoding signed-integer --bits 32 --endian big kick_a/kick_a5.sl silence 20s 0s -76d trim 0s
sox kick_a/kick_a6.wav -t sl --encoding signed-integer --bits 32 --endian big kick_a/kick_a6.sl silence 20s 0s -76d trim 0s
sox kick_b/kick_b0.wav -t sl --encoding signed-integer --bits 32 --endian big kick_b/kick_b0.sl silence 20s 0s -76d trim 0s
sox kick_b/kick_b1.wav -t sl --encoding signed-integer --bits 32 --endian big kick_b/kick_b1.sl silence 20s 0s -76d trim 0s
sox kick_b/kick_b2.wav -t sl --encoding signed-integer --bits 32 --endian big kick_b/kick_b2.sl silence 20s 0s -76d trim 0s
sox kick_b/kick_b3.wav -t sl --encoding signed-integer --bits 32 --endian big kick_b/kick_b3.sl silence 20s 0s -76d trim 0s
sox kick_b/kick_b4.wav -t sl --encoding signed-integer --bits 32 --endian big kick_b/kick_b4.sl silence 20s 0s -76d trim 0s
sox kick_b/kick_b5.wav -t sl --encoding signed-integer --bits 32 --endian big kick_b/kick_b5.sl silence 20s 0s -76d trim 0s
sox kick_b/kick_b6.wav -t sl --encoding signed-integer --bits 32 --endian big kick_b/kick_b6.sl silence 20s 0s -76d trim 0s
sox ride1/ride10.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride10.sl silence 20s 0s -76d trim 0s
sox ride1/ride11.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride11.sl silence 20s 0s -76d trim 0s
sox ride1/ride12.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride12.sl silence 20s 0s -76d trim 0s
sox ride1/ride13.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride13.sl silence 20s 0s -76d trim 0s
sox ride1/ride14.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride14.sl silence 20s 0s -76d trim 0s
sox ride1/ride15.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride15.sl silence 20s 0s -76d trim 0s
sox ride1/ride16.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride16.sl silence 20s 0s -76d trim 0s
sox ride1/ride17.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride17.sl silence 20s 0s -76d trim 0s
sox ride1/ride18.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride18.sl silence 20s 0s -76d trim 0s
sox ride1/ride19.wav -t sl --encoding signed-integer --bits 32 --endian big ride1/ride19.sl silence 20s 0s -76d trim 0s
sox ride2/ride20.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride20.sl silence 20s 0s -76d trim 0s
sox ride2/ride21.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride21.sl silence 20s 0s -76d trim 0s
sox ride2/ride22.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride22.sl silence 20s 0s -76d trim 0s
sox ride2/ride23.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride23.sl silence 20s 0s -76d trim 0s
sox ride2/ride24.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride24.sl silence 20s 0s -76d trim 0s
sox ride2/ride25.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride25.sl silence 20s 0s -76d trim 0s
sox ride2/ride26.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride26.sl silence 20s 0s -76d trim 0s
sox ride2/ride27.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride27.sl silence 20s 0s -76d trim 0s
sox ride2/ride28.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride28.sl silence 20s 0s -76d trim 0s
sox ride2/ride29.wav -t sl --encoding signed-integer --bits 32 --endian big ride2/ride29.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel0.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel0.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel1.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel1.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel2.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel2.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel3.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel3.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel4.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel4.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel5.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel5.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel6.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel6.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel7.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel7.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel8.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel8.sl silence 20s 0s -76d trim 0s
sox ride_bel/ride_bel9.wav -t sl --encoding signed-integer --bits 32 --endian big ride_bel/ride_bel9.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord0.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord0.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord1.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord1.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord2.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord2.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord3.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord3.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord4.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord4.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord5.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord5.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord6.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord6.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord7.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord7.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord8.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord8.sl silence 20s 0s -76d trim 0s
sox snare_ord/snare_ord9.wav -t sl --encoding signed-integer --bits 32 --endian big snare_ord/snare_ord9.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs0.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs0.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs1.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs1.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs2.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs2.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs3.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs3.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs4.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs4.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs5.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs5.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs6.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs6.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs7.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs7.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs8.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs8.sl silence 20s 0s -76d trim 0s
sox snare_prs/snare_prs9.wav -t sl --encoding signed-integer --bits 32 --endian big snare_prs/snare_prs9.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms0.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms0.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms1.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms1.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms2.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms2.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms3.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms3.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms4.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms4.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms5.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms5.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms6.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms6.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms7.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms7.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms8.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms8.sl silence 20s 0s -76d trim 0s
sox snare_rms/snare_rms9.wav -t sl --encoding signed-integer --bits 32 --endian big snare_rms/snare_rms9.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick0.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick0.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick1.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick1.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick2.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick2.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick3.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick3.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick4.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick4.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick5.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick5.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick6.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick6.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick7.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick7.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick8.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick8.sl silence 20s 0s -76d trim 0s
sox snare_sidestick/snare_sidestick9.wav -t sl --encoding signed-integer --bits 32 --endian big snare_sidestick/snare_sidestick9.sl silence 20s 0s -76d trim 0s
sox splash/splash0.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash0.sl silence 20s 0s -76d trim 0s
sox splash/splash1.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash1.sl silence 20s 0s -76d trim 0s
sox splash/splash2.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash2.sl silence 20s 0s -76d trim 0s
sox splash/splash3.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash3.sl silence 20s 0s -76d trim 0s
sox splash/splash4.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash4.sl silence 20s 0s -76d trim 0s
sox splash/splash5.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash5.sl silence 20s 0s -76d trim 0s
sox splash/splash6.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash6.sl silence 20s 0s -76d trim 0s
sox splash/splash7.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash7.sl silence 20s 0s -76d trim 0s
sox splash/splash8.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash8.sl silence 20s 0s -76d trim 0s
sox splash/splash9.wav -t sl --encoding signed-integer --bits 32 --endian big splash/splash9.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi0.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi0.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi1.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi1.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi2.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi2.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi3.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi3.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi4.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi4.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi5.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi5.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi6.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi6.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi7.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi7.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi8.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi8.sl silence 20s 0s -76d trim 0s
sox tom_hi/tom_hi9.wav -t sl --encoding signed-integer --bits 32 --endian big tom_hi/tom_hi9.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo0.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo0.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo1.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo1.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo2.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo2.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo3.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo3.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo4.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo4.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo5.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo5.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo6.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo6.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo7.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo7.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo8.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo8.sl silence 20s 0s -76d trim 0s
sox tom_lo/tom_lo9.wav -t sl --encoding signed-integer --bits 32 --endian big tom_lo/tom_lo9.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid0.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid0.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid1.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid1.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid2.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid2.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid3.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid3.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid4.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid4.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid5.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid5.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid6.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid6.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid7.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid7.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid8.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid8.sl silence 20s 0s -76d trim 0s
sox tom_mid/tom_mid9.wav -t sl --encoding signed-integer --bits 32 --endian big tom_mid/tom_mid9.sl silence 20s 0s -76d trim 0s
